### ISSUE TITLE
Size issue

### ISSUE THREAD

**Issue by veken1199** [Attendee/barcodeGenerator#1]
I always get 100X1 barcode size... i cannot resize the picture, if i apply css properties then the scan cannot read barcode.. is there a way to change the dimensions ?

**Comment by Attendee** [comment]
You can send parameter h*w with the function for Example 
`'barcode.generate(success,error,"12345",100,500);`

**Comment by veken1199** [comment]
Still does not work, I get "abs(stride) must be >=width " error, the only params that work are 1,1

**Comment by Attendee** [comment]
Hi. There is a way to resize. Will send you the answer tomorrow. Sleeping now.

**Comment by Attendee** [comment]
Hi again.

Here is how the parameters works.

 BarcodeGeneratorPlugin.generate(success,error,"12345",150,300,"FFFFFFFF","FFFFF000");

the parameter that we use is  “function(successCallback, errorCallback,text,height,width,color,bgColor)”

**Comment by veken1199** [comment]
thank you, it works perfectly, but i have another issue..
